# Generated by Django 4.2.7 on 2024-08-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50)),
                ('email', models.EmailField(default='email', max_length=500)),
                ('number', models.BigIntegerField(default=10)),
                ('age', models.IntegerField(default=0)),
                ('enrollment_date', models.DateField()),
                ('course', models.CharField(choices=[('python', 'Python'), ('php', 'PHP')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
